### ISSUE TITLE
OSD not working

### ISSUE THREAD

**Issue by danielk117** [OpenIPC/device-mjsxj02hl#1]
openipc 2.2.11.04

```
.osd.enabled: true
.osd.font: 
.osd.template: %F %T
.osd.corner: 
.osd.posX: -16
.osd.posY: -16
.osd.privacyMasks: 
```

wahtever settings I use, the OSD is never shown.

**Comment by danielk117** [comment]
log says `user.err majestic[922]: TTF font '/usr/share/fonts/truetype/UbuntuMono-Regular.ttf' load failed`

so I downloaded a ttf file to /root, configured it in OSD and it works all fine. 

issue could be closed. 

BTW: the autonight script doesn't seems to work right, when changing a setting and majestic restarts. it stays in day mode, but the cam is in a dark room.

**Comment by kasitoru** [comment]
For the problem with auto night, please open a new issue.
