### ISSUE TITLE
Problems with successfully flashing OpenIPC

### ISSUE THREAD

**Issue by Timisah** [OpenIPC/device-mjsxj02hl#19]
Hi,

I have had a lot of problems with flashing. Here are a few problems: 
When I flash with the SD-Card, it first lights up in orange, and a few seconds later to white for 1-2 minutes. After that time the light turns off, there is no "shutter" sound and then after 1-2 minutes it enters a bootloop (Orange and Black lights).
I have tried multiple SD-Cards, and sometimes I was succesfull with flashing, BUT then the device would not open a port nor would have a stable connection with my router (yes, I am close to it).

What am I doing wrong? Did Xiaomi change something about their camera?
Thank you for your help!

**Comment by Timisah** [comment]
Update: I just fixed it. If you need any help just ask for it and I'll be glad to help

**Comment by henrikwils** [comment]
Got similar problem, however while I did get orange LED at the first boot, and then white LED, I never got the shutter sound either, and now it appear totally dead. No LEDs or any indication of life with/without SD card and/or reset button pressed.

Any way to salvage it?

**Comment by yalgerino** [comment]
> Got similar problem, however while I did get orange LED at the first boot, and then white LED, I never got the shutter sound either, and now it appear totally dead. No LEDs or any indication of life with/without SD card and/or reset button pressed.
> 
> Any way to salvage it?

Hi,
I had the same problem, and I found the solution. Do not take the latest firmware but the one dated May 1, 2023
Look here :
https://github.com/OpenIPC/device-mjsxj02hl/issues/20

**Comment by yalgerino** [comment]
> Hi,
> 
> I have had a lot of problems with flashing. Here are a few problems: When I flash with the SD-Card, it first lights up in orange, and a few seconds later to white for 1-2 minutes. After that time the light turns off, there is no "shutter" sound and then after 1-2 minutes it enters a bootloop (Orange and Black lights). I have tried multiple SD-Cards, and sometimes I was succesfull with flashing, BUT then the device would not open a port nor would have a stable connection with my router (yes, I am close to it).
> 
> What am I doing wrong? Did Xiaomi change something about their camera? Thank you for your help!

Hi,
see my previous comment :)

Don't forget to close the issue :)
