### ISSUE TITLE
Problem with Configuration

### ISSUE THREAD

**Issue by yalgerino** [OpenIPC/device-mjsxj02hl#20]
Hi,

I do the installation steps without worries (driver with Zadig, flash with HiTool)

But as soon as I put the SD card (with the contents of the flash folder in the root),
the LED is white for 1-2 minutes, then alternates between orange and black).
I can't hear the shutter click.

The smallest SD card I have is 16GB. So I made 2 partitions of 1Go. I tested in FAT32, FAT and exFAT but still the same thing.
Between each test I reflashed with HiTool

Any idea please?
thanks in advance

**Comment by yalgerino** [comment]
OK I found it.
The WiFi configuration has been updated on OpenIPC, and is no longer compatible with our mjsxj02hl camera

Here is the link :
https://github.com/OpenIPC/firmware/blob/master/WARNING.md

You must use, as the article says, the firmware dated 01.05.2023 available on Telegram:
https://t.me/openipc_dev

**Comment by R-3MY** [comment]
Hi,

They now auto delete telegram message older than 6 months.

I'm looking for the May 1st 2023 firmware.

Regards, Rémy
