### ISSUE TITLE
Cannot install OpenIPC

### ISSUE THREAD

**Issue by darkfuncat** [OpenIPC/device-mjsxj02hl#4]
Hi,
I tried to install OpenIPC but I am stuck on step 2.
The device is only visible a second or less in my OS, and I obviously dont have time to install the driver correctly.
Any tip ?
Must press the reset button until when ?
Thanks

**Comment by kasitoru** [comment]
Try again. This must be done very quickly. I got it on the fifth try. Fortunately, this only needs to be done once.

**Comment by darkfuncat** [comment]
OK I guess it worked once (of 15-20 try) ?
Step 3 and 4 seem OK.
Now I am stuck with the configuration step 4.
Nothing happens, no led, no wifi, no click.
During step 1, you mean create 2 FAT32 partitions ? or another type? (exfat ? ntfs ?) 
With empty name ?
Nothing in the second partition ?

**Comment by kasitoru** [comment]
![image](https://user-images.githubusercontent.com/16743879/202749978-18e97a07-72fb-45dd-b641-be0693e05691.png)
Any size. All data will be on the first partition.

**Comment by darkfuncat** [comment]
OK it worked. For some reason this not the first partition to copy file but on second.
To be sure I copied on both partitions in it worked =)
Now I can access the web interface and RTSP.
Could you tell me how to install/use MQTT ? Is it in features ?
Thanks

**Comment by kasitoru** [comment]
It's not working yet. Create a new issue on this topic.
