### ISSUE TITLE
Enable MQTT feature

### ISSUE THREAD

**Issue by darkfuncat** [OpenIPC/device-mjsxj02hl#5]
Hi
I used legacy firmware previously with MQTT features (great)
Yet I installed new OpenIPC firmware and there seems to be no MQTT feature, could you please enable it ?
Thanks

**Comment by kasitoru** [comment]
Done. Services -> MQTT client

**Comment by darkfuncat** [comment]
Hi,
Sorry for long time response, I had no time to work with this.
I have done some tests with your new package.
I can now see the MQTT section in Service.
I filled all data but nothing happens, perhaps I missed something ?
What kind of MQTT message are sent ?
Thanks

**Comment by kasitoru** [comment]
Is there item "Send to MQTT" in the "Motion guard"?

**Comment by darkfuncat** [comment]
Hello,
No, there is only email, FTP, Telegram, webhook, Yandex Disk, speaker

**Comment by kasitoru** [comment]
Upgrade the web interface from the development branch (Updates -> Web Interface -> Branch -> Development).

**Comment by kasitoru** [comment]
It is also necessary to wait for the fix of this problem https://github.com/OpenIPC/microbe-web/issues/112

**Comment by darkfuncat** [comment]
OK, I did upgrade (both firmware & web to dev)
I see now the "Send to MQTT" in the "Motion guard" but does nothing.
I suppose this is linked to your previous post and have to wait.

**Comment by darkfuncat** [comment]
Hi,
Done see other ticket.
Even I there is only one message available ? "alarm ON" I presume ?
Previously there were alaem ON, alarm OFF, alarm Human ... it was more complete =)
Thanks

**Comment by kasitoru** [comment]
> Even I there is only one message available ? "alarm ON" I presume ?

Yes. For Home Assistant use flag [`off_delay`](https://www.home-assistant.io/integrations/binary_sensor.mqtt/#off_delay).
