### ISSUE TITLE
Send FTP alarm is not triggered with Motion guard

### ISSUE THREAD

**Issue by darkfuncat** [OpenIPC/device-mjsxj02hl#6]
Hello,
I try to use motion guard feature to send video and snapshot files via FTP.
I have configured the send FTP section OK.
But there is no push to ftp.
Note that I also try to execute command "send2ftp.sh" and it work well (send a good snapshot)

**Comment by kasitoru** [comment]
You must configure FTP (Services -> Send to FTP), enable Motion guard (Services -> Motion guard) and check "Upload to FTP".

**Comment by kasitoru** [comment]
Also motion detection option should be enabled (Majestic -> In-Camera Motion Detection).

**Comment by darkfuncat** [comment]
Hi @kasitoru 
I am trying your new latest firmware.
I enabled FTP, motionguard with FTP and In-Camera Motion detection but nothing happens.
On the other hand, please note that "send2ftp.sh" works well.
Perhaps did I miss something ?

Edit :
After many reset/reboot nothing changes.
BUT, after one long reboot AND replacement of power supply, now it is working ... very strange ?
