### ISSUE TITLE
With OpenIPC : Motion guard sensitivity KO

### ISSUE THREAD

**Issue by darkfuncat** [OpenIPC/device-mjsxj02hl#7]
Hi,
Another report with OpenIPC.
The sensibility of motion guard is extrem, event with motion sensitivity to 1 (of 1-50)
I guess that this control does nothing.
Is there any action to control the real sensitivity ?
Thanks

**Comment by kasitoru** [comment]
This question does not apply to Xiaomi MJSXJ02HL camera support.
Ask about it here https://github.com/OpenIPC/microbe-web/issues
