### ISSUE TITLE
Unable to flash u-boot-hi3518ev300-universal.bin

### ISSUE THREAD

**Issue by VanrVanr** [OpenIPC/device-mjsxj02hl#8]
Hello,
I am unable to flash u-boot-hi3518ev300-universal.bin
![errcam](https://user-images.githubusercontent.com/19372048/207954633-d62b8edb-ce48-4333-a442-679c1674b44b.jpg)

```
`##################################################### ---- 10%
################################################### ---- 20%
################################################### ---- 30%
################################################### ---- 40%
################################################### ---- 50%
################################################### ---- 60%
################################################### ---- 70%
################################################### ---- 80%
################################################### ---- 90%
################################################### ---- 100%
Boot download completed!
Failed to wait boot running!
There may be no boot on the board.

Please check if the boot is correct!
Failed to download fastboot!

USB channels were closed successfully.
`
```

If I try to flash uboot.bin from https://kasito.ru/wp-content/uploads/2021/03/uboot_patcher.zip it works fine but as I understand it is incompatible with OpenIPC firmware.

So it doesn't look like it's camera hardware issue (memory) because it only happens with u-boot-hi3518ev300-universal.bin
How it is possible to fix this?

Thanks.

**Comment by kasitoru** [comment]
Try it (use [custom firmware](https://github.com/kasitoru/mjsxj02hl_firmware) and telnet):
```
flash_eraseall /dev/mtd0
sync
flashcp -v /mnt/mmc/u-boot-hi3518ev300-universal.bin /dev/mtd0
```
File `u-boot-hi3518ev300-universal.bin` must be located on the memory card.

**Comment by VanrVanr** [comment]
Thank you, but unfortunately I am getting same error when I try to flash kernel and rootfs, it looks like fastboot is flashed but not booting when the camera is on.

**Comment by kasitoru** [comment]
The output of UART messages is needed.

**Comment by VanrVanr** [comment]
Here is the output of uart:
`
hifmc_spi_nor_probe(1759): SPI Nor ID Table Version 1.0
SPI Nor(cs 0) ID: 0x5e 0x40 0x18 can't find in the ID table !!!
*** Warning - spi_flash_probe() failed, using default environment
`

**Comment by kasitoru** [comment]
SPI memory chip is missing from the `hifmc_spi_nor_info_table` https://github.com/OpenIPC/u-boot-hi3516ev200/blob/43dc69853218fe33c4cc2e061e13bd097c266ca7/drivers/mtd/spi/hifmc100/hifmc_spi_nor_ids.c#L296

Take a high-quality photo of the chip in macro mode.

**Comment by VanrVanr** [comment]
![hip](https://user-images.githubusercontent.com/19372048/208060452-f75ec8c9-6c43-47d9-bb01-1765f1b15c7a.jpg)

**Comment by VanrVanr** [comment]
![hip](https://user-images.githubusercontent.com/19372048/208063178-ce3a6390-02e1-4884-bb28-d4cce84a42e4.jpg)

**Comment by kasitoru** [comment]
PR https://github.com/OpenIPC/u-boot-hi3516ev200/pull/1
