### ISSUE TITLE
Problem with fastboot

### ISSUE THREAD

**Issue by darkblackarts** [OpenIPC/device-mjsxj02hl#9]
Hi,
I tried to install this software, unfortunately when trying to upload u-boot-hi3518ev300-universal.bin to fastboot I get an error:
################################################### ---- 60%
################Failed to send data frame, check that the serial port is normal.
Failed to download File!
Please check if the boot is correct!
Failed to download fastboot!

USB channels were closed successfully.

When I use https://kasito.ru/wp-content/uploads/2021/03/uboot_patcher.zip is working fine

**Comment by kasitoru** [comment]
Check the partition table. You need to use [this file](https://raw.githubusercontent.com/OpenIPC/device-mjsxj02hl/master/usb-burn.xml). Also try using a different cable and USB port.

**Comment by darkblackarts** [comment]
I'm an idiot xD 
I tried from another computer and no error.

One more question, should the remaining partitions be wiped?
![image](https://user-images.githubusercontent.com/25610646/213261659-55f2ee38-aff5-4b0b-992c-cead8284e9c0.png)

**Comment by kasitoru** [comment]
Click OK

**Comment by darkblackarts** [comment]
It works :D
Thank you very much
